name: sweetipie
description: "A cake shop e-commerce application"
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pocketbase: ^0.23.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/